export * from "./set-pokedex.hook.function";
export * from "./next-pokdex.hook.function";
export * from "./set-pokedex.hook.function";
export * from "./add-pokemon.hook.function";
export * from "./set-enemy.function";
export * from "./ally-atack.hook.function";
export * from "./enemy-atack.hook.function";
export * from "./start-battle.hook.function";
export * from "./run.hook.function";