enum POKEDEX_TYPE {
    SET_POKEDEX,
    ADD_POKEMON,
    SET_CURR_POKEMON,
    SET_ENEMY,
    ALLY_ATACK,
    ENEMY_ATACK,
    START_BATTLE,
    RUN,
    CAPTURE,
    GOT_TO_MEDIC,
    GO_TO_POKEDEX,
}

export { POKEDEX_TYPE }